branch-defaults:
  default:
    environment: taskenv
    group_suffix: null
global:
  application_name: env
  branch: null
  default_ec2_keyname: task2
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
